# Generated by Django 4.0.5 on 2022-07-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombreCompleto',
            new_name='nombre',
        ),
    ]
