# Generated by Django 4.0.5 on 2022-07-15 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=30, verbose_name='Nombre Usuario')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['idUsuario'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id')),
                ('marca1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.marca')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['idProveedor'],
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('idBeneficio', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelBeneficio', models.IntegerField(verbose_name='Nivel')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
            ],
            options={
                'verbose_name': 'beneficio',
                'verbose_name_plural': 'beneficios',
                'ordering': ['idBeneficio'],
            },
        ),
    ]
