# Generated by Django 4.0.5 on 2022-07-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_usuario_proveedor_beneficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='marca1',
        ),
        migrations.DeleteModel(
            name='Beneficio',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
